name: travis_anaconda_jupyter
channels:
- defaults
dependencies:
- python=3.7.3
- numpy==1.17.3
- pandas==0.24.2
- matplotlib==3.1.0
- seaborn==0.9.0
- jupyter==1.0
- networkx==2.4
- path==13.1.0
- pytest==5.0.1